<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css"/>
<link href="/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
<link href="/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css"/>
<link href="/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
<link href="/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
<!-- END GLOBAL MANDATORY STYLES -->
<!-- BEGIN THEME STYLES -->
<link href="/css/components.css" rel="stylesheet" type="text/css"/>
<link href="/css/plugins.css" rel="stylesheet" type="text/css"/>
<link href="/css/layout.css" rel="stylesheet" type="text/css"/>
<link href="/css/themes/light.css" rel="stylesheet" type="text/css"/>
<link href="/css/custom.css" rel="stylesheet" type="text/css"/>
<link href="/css/skins/square/green.css" rel="stylesheet">

<link href="//cdn.datatables.net/1.10.0/css/jquery.dataTables.css" rel="stylesheet" type="text/css"/>
<link href="http://datatables.net/release-datatables/extensions/FixedHeader/css/dataTables.fixedHeader.css" rel="stylesheet" type="text/css"/>
		
<!-- END THEME STYLES -->
<link rel="shortcut icon" href="favicon.ico"/>




<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<!--[if lt IE 9]>
<script src="/js/respond.min.js"></script>
<script src="/js/excanvas.min.js"></script> 
<![endif]-->
<script src="/js/jquery-1.11.1.min.js" type="text/javascript"></script>
<script src="/js/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
<script src="/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
<script src="/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="/js/jquery.blockui.min.js" type="text/javascript"></script>

<script src="/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<script src="/js/metronic.js" type="text/javascript"></script>
<script src="/js/layout.js" type="text/javascript"></script>
<script src="/js/icheck.js"></script>

<script src="//cdn.datatables.net/1.10.0/js/jquery.dataTables.js" type="text/javascript"></script>
<script src="http://datatables.net/release-datatables/extensions/FixedHeader/js/dataTables.fixedHeader.js" type="text/javascript"></script>
		
<script>
jQuery(document).ready(function() {    
    Metronic.init(); // init metronic core components
	Layout.init(); // init current layout
});
</script>